name: Deploy Flutter Web to GitHub Pages (Development)

on:
  push:
    branches: [ web-development ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - uses: bluefireteam/flutter-gh-pages@v9
      with:
        baseHref: /SentienWork/
        token: ${{ secrets.GITHUB_TOKEN }}
